import { AgentRole } from '@/types';
import {
  UserGroupIcon,
  CpuChipIcon,
  CodeBracketIcon,
  ChartBarIcon,
  TableCellsIcon,
  DocumentTextIcon,
  CheckBadgeIcon,
  LightBulbIcon,
  WrenchScrewdriverIcon,
  AcademicCapIcon,
  ChatBubbleBottomCenterTextIcon,
  SparklesIcon as SparklesIconOutline,
  ArchiveBoxIcon,
  TrashIcon,
  PrinterIcon,
  BoltIcon,
  UserCircleIcon,
  SquaresPlusIcon as AliasedCreatePlanIcon, 
  BeakerIcon as ElaborateTaskIcon,
  DocumentArrowDownIcon as SaveToDocumentIcon,
  DocumentMagnifyingGlassIcon,
  EyeIcon,
  PlayCircleIcon,
  CogIcon as ProcessingIcon,
  Cog6ToothIcon,
  ArrowPathIcon as ReElaborateIcon,
  MagnifyingGlassIcon as SearchIcon,
  PencilSquareIcon as EditIcon,
  CheckCircleIcon as SaveChangesIcon,
  ChatBubbleLeftRightIcon,
  PaperAirplaneIcon,
  PlusCircleIcon,
  RectangleStackIcon,
  ArrowDownOnSquareIcon,
  CubeTransparentIcon,
  DocumentPlusIcon,
  ArrowDownTrayIcon
} from '@heroicons/react/24/outline';
import { SparklesIcon as SparklesIconSolid } from '@heroicons/react/24/solid';

export const GEMINI_MODEL_TEXT = 'gemini-2.5-flash-preview-04-17';
export const GEMINI_MODEL_IMAGE = 'imagen-3.0-generate-002';

interface AgentAppearance {
  description: string;
  icon: React.ElementType;
  colorClass: string;
  base: string;
  textColor: string;
  borderColor: string;
}

export const AGENT_ROLE_COLORS: Record<string, { base: string, textColor: string, borderColor: string }> = {
    sky: { base: 'bg-sky-900/50', textColor: 'text-sky-300', borderColor: 'border-sky-500' },
    indigo: { base: 'bg-indigo-900/50', textColor: 'text-indigo-300', borderColor: 'border-indigo-500' },
    emerald: { base: 'bg-emerald-900/50', textColor: 'text-emerald-300', borderColor: 'border-emerald-500' },
    amber: { base: 'bg-amber-900/50', textColor: 'text-amber-300', borderColor: 'border-amber-500' },
    rose: { base: 'bg-rose-900/50', textColor: 'text-rose-300', borderColor: 'border-rose-500' },
    slate: { base: 'bg-slate-700/50', textColor: 'text-slate-300', borderColor: 'border-slate-500' },
    cyan: { base: 'bg-cyan-900/50', textColor: 'text-cyan-300', borderColor: 'border-cyan-500' },
    fuchsia: { base: 'bg-fuchsia-900/50', textColor: 'text-fuchsia-300', borderColor: 'border-fuchsia-500' },
};

export const AGENT_ROLE_DETAILS: Record<AgentRole, AgentAppearance> = {
  [AgentRole.ProjectManager]: { description: "Sledovanie timeline, resource allocation, risk assessment.", icon: UserGroupIcon, colorClass: 'sky', ...AGENT_ROLE_COLORS.sky },
  [AgentRole.TechnicalArchitect]: { description: "Systémový design, technology stack selection.", icon: CpuChipIcon, colorClass: 'indigo', ...AGENT_ROLE_COLORS.indigo },
  [AgentRole.Developer]: { description: "Code implementation, testing, code documentation.", icon: CodeBracketIcon, colorClass: 'emerald', ...AGENT_ROLE_COLORS.emerald },
  [AgentRole.BusinessAnalyst]: { description: "Requirements gathering, user story creation.", icon: ChartBarIcon, colorClass: 'amber', ...AGENT_ROLE_COLORS.amber },
  [AgentRole.DataAnalyst]: { description: "Data collection, statistical analysis, visualization.", icon: TableCellsIcon, colorClass: 'rose', ...AGENT_ROLE_COLORS.rose },
  [AgentRole.DocumentationSpecialist]: { description: "Technical documentation, user manuals, API docs.", icon: DocumentTextIcon, colorClass: 'slate', ...AGENT_ROLE_COLORS.slate },
  [AgentRole.QATesting]: { description: "Test plan creation, automated testing, bug tracking.", icon: CheckBadgeIcon, colorClass: 'cyan', ...AGENT_ROLE_COLORS.cyan },
  [AgentRole.CreativeContent]: { description: "UI/UX design concepts, marketing materials.", icon: LightBulbIcon, colorClass: 'fuchsia', ...AGENT_ROLE_COLORS.fuchsia },
};

export const PROJECT_TYPES_EXAMPLES = [
  "Vývoj webovej aplikácie pre e-commerce s platobnou bránou a správou produktov",
  "Analýza trhových trendov v oblasti AI a vytvorenie interaktívneho dashboardu",
  "Vytvorenie technickej dokumentácie pre nový softvér vrátane API a návodov",
  "Naplánovanie marketingovej kampane pre uvedenie mobilnej aplikácie na trh",
  "Návrh a implementácia CRM systému pre malý podnik na mieru",
  "Vytvorenie online platformy pre vzdelávacie kurzy s video obsahom a certifikáciou",
  "Analýza zákazníckych dát za účelom personalizácie ponuky v e-shope",
  "Vývoj mobilnej hry pre Android a iOS s in-app nákupmi",
  "Redizajn a optimalizácia existujúcej webovej stránky pre lepšiu konverziu a SEO",
  "Automatizácia interných firemných procesov pomocou softvérového robota (RPA)"
];

export const UI_STRINGS = {
  appName: "Multi-Agent Projektový Orchestrátor",
  submitButton: "Orchestrovať Projekt",
  projectTitleLabel: "Názov Projektu",
  projectTitlePlaceholder: "Zadajte názov vášho projektu...",
  projectDescriptionLabel: "Popis Projektu",
  projectDescriptionPlaceholder: "Zadajte detailný popis vášho projektu alebo požiadavky...",
  generatingTeam: "Skladám optimálny tím...",
  generatingAgentTasks: "Generujem počiatočné úlohy...",
  executingInitialTasks: "Spracovávam počiatočné úlohy agentov...",
  interpretingRequest: "Interpretujem požiadavku...",
  generatingDocs: "Generujem osnovu dokumentácie...",
  errorOccurred: "Vyskytla sa chyba",
  defaultError: "Neznáma chyba. Skúste to prosím znova.",
  teamComposition: "Zloženie Tímu Agentov",
  documentation: "Projektová Dokumentácia",
  generateOutline: "Generovať Osnovu Dokumentácie",
  projectDetails: "Detaily Projektu",
  projectType: "Typ Projektu",
  goals: "Ciele",
  expertiseNeeded: "Potrebná Expertíza",
  originalRequest: "Pôvodná Požiadavka",
  projectHistory: "História Projektov",
  viewProjectDetails: "Zobraziť Detaily",
  clearHistory: "Vymazať Históriu",
  noHistory: "Žiadne projekty v histórii.",
  closeModal: "Zavrieť",
  orchestratedOn: "Orchestrované",
  newRequest: "Nová Požiadavka",
  confirmClearHistory: "Naozaj chcete vymazať celú históriu projektov? Táto akcia je nevratná.",
  printAction: "Tlačiť",
  agentTaskOutputLabel: "Výstup Úlohy Agenta",
  agentStatusIdle: "Nečinný",
  agentStatusActive: "Spracováva",
  agentStatusCompleted: "Úloha Dokončená",
  agentIsWorking: "Spracovávam...",
  apiKeyNotConfigured: "API kľúč nie je nakonfigurovaný. Skontrolujte premennú prostredia API_KEY.",
  aiResponseParseError: "Nepodarilo sa spracovať odpoveď od AI. Skúste to prosím znova.",
  aiSafetyBlockedError: "Odpoveď bola blokovaná z bezpečnostných dôvodov. Skúste preformulovať vašu požiadavku.",
  errorInterpretingRequest: "Chyba pri interpretácii požiadavky",
  errorGeneratingAgentTask: "Chyba pri generovaní úlohy pre agenta",
  errorExecutingAgentTask: "Chyba pri spracovaní úlohy agentom",
  errorGeneratingDocOutline: "Chyba pri generovaní osnovy dokumentácie",
  errorDuringSearch: "Chyba počas vyhľadávania",
  generateNewPlanButton: "Generovať Exekučný Plán",
  generatingNewPlan: "Generujem nový exekučný plán...",
  allAgentTasksMustBeCompleted: "Pre generovanie plánu musia byť dokončené úlohy všetkých agentov.",
  newExecutionPlanTitle: "Exekučný Plán Projektu",
  elaborateSubTaskButton: "Vypracovať",
  elaboratingSubTaskContent: "Generujem obsah pod-úlohy...",
  elaboratingContent: "Spracovávam obsah...",
  subTaskStatusPending: "Čaká",
  subTaskStatusGenerating: "Generuje sa...",
  subTaskStatusSavedToDocument: "Uložené",
  savingToDocument: "Ukladám do dokumentu...",
  errorGeneratingNewPlan: "Chyba pri generovaní nového exekučného plánu",
  errorElaboratingSubTask: "Chyba pri vypracovaní obsahu pod-úlohy",
  phaseDocumentsTitle: "Dokumenty Fáz",
  viewDocumentButton: "Zobraziť Dokument",
  closeDocumentViewerButton: "Zavrieť",
  noDocumentsGenerated: "Zatiaľ neboli vygenerované žiadne dokumenty.",
  documentLastModified: "Posledná úprava",
  elaborateEntirePhaseButton: "Vypracovať Celú Fázu",
  processingEntirePhase: "Spracovávam celú fázu...",
  phaseStatusIdle: "Fáza čaká",
  phaseStatusProcessing: "Spracováva sa",
  phaseStatusCompletedAll: "Všetky úlohy hotové",
  errorProcessingEntirePhase: "Chyba pri spracovaní celej fázy",
  reElaborateSubTaskButton: "Prepracovať",
  searchRelatedInfoButton: "Vyhľadať",
  searchPromptTitle: "Zadajte dopyt pre vyhľadávanie",
  searchPromptDefault: "Hľadám informácie o: ",
  searchResultsTitle: "Výsledky Vyhľadávania",
  searchNoResults: "Nenašli sa žiadne relevantné informácie.",
  searchSource: "Zdroj",
  editDocumentButton: "Upraviť",
  saveDocumentChangesButton: "Uložiť Zmeny",
  documentUpdatedSuccessfully: "Dokument bol úspešne aktualizovaný.",
  errorUpdatingDocument: "Chyba pri aktualizácii dokumentu.",
  subTaskProgress: "Priebeh pod-úloh fázy",
  rateLimitError: "Bol prekročený limit počtu požiadaviek na AI službu. Skúste to prosím o chvíľu znova, alebo skontrolujte nastavenia svojho API plánu.",
  settings: "Nastavenia",
  settingsModalTitle: "Nastavenia Aplikácie",
  settingsGeneralTab: "Všeobecné",
  settingsAITab: "Model AI",
  settingsAPITab: "API Kľúč",
  settingsThemeLabel: "Vzhľad aplikácie",
  settingsThemeDark: "Tmavý",
  settingsThemeLight: "Svetlý",
  settingsAIAssistantDisplayMode: "Zobrazenie AI Asistenta",
  settingsAIAssistantDisplayModeNone: "Nezobraziť",
  settingsAIAssistantDisplayModeFab: "Plávajúce tlačidlo",
  settingsAIAssistantDisplayModeTab: "Záložka v pracovnom priestore",
  settingsAIAssistantDisplayModeSidebarLeft: "Postranný panel (vľavo)",
  settingsAIAssistantDisplayModeSidebarRight: "Postranný panel (vpravo)",
  settingsHeaderButtonMode: "Tlačidlá v hlavičke",
  settingsHeaderButtonModeIconAndText: "Ikona a text",
  settingsHeaderButtonModeIconOnly: "Iba ikona",
  settingsAITemperatureLabel: "Teplota (Kreativita)",
  settingsAITemperatureDescription: "Nižšie hodnoty znamenajú viac deterministické odpovede, vyššie hodnoty sú kreatívnejšie.",
  settingsAITopPLabel: "Top-P",
  settingsAITopPDescription: "Ovplyvňuje výber slov. Menšie číslo obmedzuje výber na pravdepodobnejšie slová.",
  settingsAITopKLabel: "Top-K",
  settingsAITopKDescription: "Obmedzuje výber slov na K najpravdepodobnejších slov.",
  settingsSaveButton: "Uložiť Nastavenia",
  settingsResetButton: "Obnoviť Predvolené",
  settingsApiCallDelay: "Oneskorenie API volaní (ms)",
  settingsApiCallDelayDescription: "Čas v milisekundách medzi jednotlivými požiadavkami na AI. Pomáha predchádzať chybám rate-limitingu.",
  apiKeyStatus: "Stav API Kľúča",
  apiKeyDetected: "API kľúč bol úspešne detegovaný.",
  apiKeyNotDetected: "API kľúč nebol nájdený v premenných prostredia.",
  apiKeyHowTo: "Ako získať API kľúč?",
  apiKeyGetHere: "Získajte kľúč v Google AI Studio",
  aiAssistantTitle: "AI Asistent",
  aiAssistantChatPlaceholder: "Spýtajte sa ma na projekt...",
  aiAssistantRefineDescription: "Vylepšiť s AI",
  aiAssistantRefining: "Vylepšujem...",
  aiAssistantSuggestionsTitle: "Tu je pár nápadov:",
  aiAssistantWelcome: "Dobrý deň! Som váš AI asistent. Ako vám môžem pomôcť s týmto projektom?",
  aiAssistantError: "Ospravedlňujem sa, vyskytla sa chyba v komunikácii.",
  incorporateSuggestion: "Zapracovať",
  dynamicTabContentTitle: "Obsah vygenerovaný AI",
  dynamicTabContinueWithAI: "Pokračovať s AI",
  dynamicTabContinueWithAIPrompt: "Zadajte inštrukciu pre ďalšie spracovanie obsahu:",
  dynamicTabSaveToDocs: "Uložiť do Dokumentov",
  createMiniApp: "Vytvoriť Miniaplikáciu",
  miniAppWorkspaceTitle: "Pracovný Priestor Miniaplikácií",
  miniAppIdeasTitle: "Sugestívne Návrhy na Miniaplikácie",
  generatingMiniAppIdeas: "Generujem nápady na miniaplikácie...",
  createMiniAppButton: "Vytvoriť",
  creatingMiniApp: "Vytváram miniaplikáciu...",
  errorGeneratingMiniAppIdeas: "Chyba pri generovaní nápadov na miniaplikácie.",
  errorCreatingMiniApp: "Chyba pri vytváraní miniaplikácie.",
  miniAppViewerTitle: "Náhľad Miniaplikácie",
  miniAppSettings: "Nastavenia Miniaplikácie",
  miniAppCodeEditor: "Editor Kódu",
  miniAppAIAgent: "AI Agent Miniaplikácie",
  customMiniAppInputLabel: "Zadajte vlastný nápad na miniaplikáciu",
  optimizeAndCreateButton: "Optimalizovať & Vytvoriť",
  optimizingPrompt: "Optimalizujem prompt...",
  moreSuggestionsButton: "Ďalšie Návrhy",
  generatingMoreSuggestions: "Generujem ďalšie návrhy...",
  errorOptimizingPrompt: "Chyba pri optimalizácii promptu.",
  saveToDocumentation: "Uložiť do Dokumentácie",
  downloadMiniApp: "Stiahnuť Miniaplikáciu",
};

export const GENERIC_ICONS = {
  Phase: WrenchScrewdriverIcon,
  Document: DocumentTextIcon,
  Analysis: AcademicCapIcon,
  Report: ChatBubbleBottomCenterTextIcon,
  Code: CodeBracketIcon,
  Design: SparklesIconOutline,
  History: ArchiveBoxIcon,
  Clear: TrashIcon,
  Printer: PrinterIcon,
  ExecuteTask: BoltIcon,
  AssignedAgent: UserCircleIcon,
  CreatePlan: AliasedCreatePlanIcon, 
  ElaborateTask: ElaborateTaskIcon,
  SaveToDocument: SaveToDocumentIcon,
  DocumentsList: DocumentMagnifyingGlassIcon,
  ViewDocument: EyeIcon,
  ElaboratePhase: PlayCircleIcon,
  Processing: ProcessingIcon,
  ReElaborateTask: ReElaborateIcon,
  Refresh: ReElaborateIcon,
  Search: SearchIcon,
  Edit: EditIcon,
  SaveChanges: SaveChangesIcon,
  Settings: Cog6ToothIcon,
  AIAssistant: ChatBubbleLeftRightIcon,
  Send: PaperAirplaneIcon,
  Refine: SparklesIconSolid,
  NewRequest: PlusCircleIcon,
  DynamicTab: RectangleStackIcon,
  Incorporate: ArrowDownOnSquareIcon,
  MiniApp: CubeTransparentIcon,
  SaveToDocs: DocumentPlusIcon,
  Download: ArrowDownTrayIcon,
};

export const LOCAL_STORAGE_HISTORY_KEY = 'mapo_project_history';
export const LOCAL_STORAGE_SETTINGS_KEY = 'mapo_app_settings';

export const ALL_AGENT_ROLES_ORDERED: AgentRole[] = [
  AgentRole.ProjectManager,
  AgentRole.TechnicalArchitect,
  AgentRole.BusinessAnalyst,
  AgentRole.Developer,
  AgentRole.DataAnalyst,
  AgentRole.QATesting,
  AgentRole.DocumentationSpecialist,
  AgentRole.CreativeContent,
];

export const MAX_AGENTS_PER_ROLE: Record<AgentRole, number> = {
  [AgentRole.ProjectManager]: 1,
  [AgentRole.TechnicalArchitect]: 1,
  [AgentRole.BusinessAnalyst]: 1,
  [AgentRole.Developer]: 2, 
  [AgentRole.DataAnalyst]: 1,
  [AgentRole.QATesting]: 1,
  [AgentRole.DocumentationSpecialist]: 1,
  [AgentRole.CreativeContent]: 1,
};